// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"time"

	externalRef5 "github.com/render-oss/sdk/go/pkg/render/internal/client/envvar"
)

// Defines values for BuildRunRuntime.
const (
	BuildRunRuntimeDocker BuildRunRuntime = "docker"
	BuildRunRuntimeElixir BuildRunRuntime = "elixir"
	BuildRunRuntimeGo     BuildRunRuntime = "go"
	BuildRunRuntimeNode   BuildRunRuntime = "node"
	BuildRunRuntimePython BuildRunRuntime = "python"
	BuildRunRuntimeRuby   BuildRunRuntime = "ruby"
	BuildRunRuntimeRust   BuildRunRuntime = "rust"
)

// Valid indicates whether the value is a known member of the BuildRunRuntime enum.
func (e BuildRunRuntime) Valid() bool {
	switch e {
	case BuildRunRuntimeDocker:
		return true
	case BuildRunRuntimeElixir:
		return true
	case BuildRunRuntimeGo:
		return true
	case BuildRunRuntimeNode:
		return true
	case BuildRunRuntimePython:
		return true
	case BuildRunRuntimeRuby:
		return true
	case BuildRunRuntimeRust:
		return true
	default:
		return false
	}
}

// Defines values for BuildRunStatus.
const (
	Canceled   BuildRunStatus = "canceled"
	Created    BuildRunStatus = "created"
	Failed     BuildRunStatus = "failed"
	InProgress BuildRunStatus = "inProgress"
	Succeeded  BuildRunStatus = "succeeded"
	Unknown    BuildRunStatus = "unknown"
)

// Valid indicates whether the value is a known member of the BuildRunStatus enum.
func (e BuildRunStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Created:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case Succeeded:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for BuildSourceGitRegion.
const (
	BuildSourceGitRegionFrankfurt BuildSourceGitRegion = "frankfurt"
	BuildSourceGitRegionOhio      BuildSourceGitRegion = "ohio"
	BuildSourceGitRegionOregon    BuildSourceGitRegion = "oregon"
	BuildSourceGitRegionSingapore BuildSourceGitRegion = "singapore"
	BuildSourceGitRegionVirginia  BuildSourceGitRegion = "virginia"
)

// Valid indicates whether the value is a known member of the BuildSourceGitRegion enum.
func (e BuildSourceGitRegion) Valid() bool {
	switch e {
	case BuildSourceGitRegionFrankfurt:
		return true
	case BuildSourceGitRegionOhio:
		return true
	case BuildSourceGitRegionOregon:
		return true
	case BuildSourceGitRegionSingapore:
		return true
	case BuildSourceGitRegionVirginia:
		return true
	default:
		return false
	}
}

// Defines values for BuildSourceGitRuntime.
const (
	BuildSourceGitRuntimeDocker BuildSourceGitRuntime = "docker"
	BuildSourceGitRuntimeElixir BuildSourceGitRuntime = "elixir"
	BuildSourceGitRuntimeGo     BuildSourceGitRuntime = "go"
	BuildSourceGitRuntimeNode   BuildSourceGitRuntime = "node"
	BuildSourceGitRuntimePython BuildSourceGitRuntime = "python"
	BuildSourceGitRuntimeRuby   BuildSourceGitRuntime = "ruby"
	BuildSourceGitRuntimeRust   BuildSourceGitRuntime = "rust"
)

// Valid indicates whether the value is a known member of the BuildSourceGitRuntime enum.
func (e BuildSourceGitRuntime) Valid() bool {
	switch e {
	case BuildSourceGitRuntimeDocker:
		return true
	case BuildSourceGitRuntimeElixir:
		return true
	case BuildSourceGitRuntimeGo:
		return true
	case BuildSourceGitRuntimeNode:
		return true
	case BuildSourceGitRuntimePython:
		return true
	case BuildSourceGitRuntimeRuby:
		return true
	case BuildSourceGitRuntimeRust:
		return true
	default:
		return false
	}
}

// Defines values for BuildSourcePATCHGitRegion.
const (
	BuildSourcePATCHGitRegionFrankfurt BuildSourcePATCHGitRegion = "frankfurt"
	BuildSourcePATCHGitRegionOhio      BuildSourcePATCHGitRegion = "ohio"
	BuildSourcePATCHGitRegionOregon    BuildSourcePATCHGitRegion = "oregon"
	BuildSourcePATCHGitRegionSingapore BuildSourcePATCHGitRegion = "singapore"
	BuildSourcePATCHGitRegionVirginia  BuildSourcePATCHGitRegion = "virginia"
)

// Valid indicates whether the value is a known member of the BuildSourcePATCHGitRegion enum.
func (e BuildSourcePATCHGitRegion) Valid() bool {
	switch e {
	case BuildSourcePATCHGitRegionFrankfurt:
		return true
	case BuildSourcePATCHGitRegionOhio:
		return true
	case BuildSourcePATCHGitRegionOregon:
		return true
	case BuildSourcePATCHGitRegionSingapore:
		return true
	case BuildSourcePATCHGitRegionVirginia:
		return true
	default:
		return false
	}
}

// Defines values for BuildSourcePATCHGitRuntime.
const (
	BuildSourcePATCHGitRuntimeDocker BuildSourcePATCHGitRuntime = "docker"
	BuildSourcePATCHGitRuntimeElixir BuildSourcePATCHGitRuntime = "elixir"
	BuildSourcePATCHGitRuntimeGo     BuildSourcePATCHGitRuntime = "go"
	BuildSourcePATCHGitRuntimeNode   BuildSourcePATCHGitRuntime = "node"
	BuildSourcePATCHGitRuntimePython BuildSourcePATCHGitRuntime = "python"
	BuildSourcePATCHGitRuntimeRuby   BuildSourcePATCHGitRuntime = "ruby"
	BuildSourcePATCHGitRuntimeRust   BuildSourcePATCHGitRuntime = "rust"
)

// Valid indicates whether the value is a known member of the BuildSourcePATCHGitRuntime enum.
func (e BuildSourcePATCHGitRuntime) Valid() bool {
	switch e {
	case BuildSourcePATCHGitRuntimeDocker:
		return true
	case BuildSourcePATCHGitRuntimeElixir:
		return true
	case BuildSourcePATCHGitRuntimeGo:
		return true
	case BuildSourcePATCHGitRuntimeNode:
		return true
	case BuildSourcePATCHGitRuntimePython:
		return true
	case BuildSourcePATCHGitRuntimeRuby:
		return true
	case BuildSourcePATCHGitRuntimeRust:
		return true
	default:
		return false
	}
}

// Build defines model for build.
type Build struct {
	AssetsDeletedAt *time.Time `json:"assetsDeletedAt,omitempty"`

	// BuildRun The Render build run that produced this build. Present when the build source is currently build-based. Mutually exclusive with `image`.
	BuildRun      *BuildRun     `json:"buildRun,omitempty"`
	BuildSourceId BuildSourceId `json:"buildSourceId"`
	CreatedAt     time.Time     `json:"createdAt"`
	Id            BuildId       `json:"id"`

	// Image Present when the build source is currently image-based. Mutually exclusive with `buildRun`.
	Image     *Image    `json:"image,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
type BuildFilter struct {
	IgnoredPaths []string `json:"ignoredPaths"`
	Paths        []string `json:"paths"`
}

// BuildId defines model for buildId.
type BuildId = string

// BuildRun The Render build run that produced this build. Present when the build source is currently build-based. Mutually exclusive with `image`.
type BuildRun struct {
	BuildFinishedAt *time.Time       `json:"buildFinishedAt,omitempty"`
	BuildStartedAt  *time.Time       `json:"buildStartedAt,omitempty"`
	CommitId        *string          `json:"commitId,omitempty"`
	CommitUrl       *string          `json:"commitUrl,omitempty"`
	Id              string           `json:"id"`
	Runtime         *BuildRunRuntime `json:"runtime,omitempty"`
	Status          *BuildRunStatus  `json:"status,omitempty"`
}

// BuildRunRuntime defines model for BuildRun.Runtime.
type BuildRunRuntime string

// BuildRunStatus defines model for BuildRun.Status.
type BuildRunStatus string

// BuildSource defines model for buildSource.
type BuildSource struct {
	CreatedAt time.Time `json:"createdAt"`

	// Git Present when the build source is currently build-based. Mutually exclusive with `image`.
	Git *BuildSourceGit `json:"git,omitempty"`
	Id  BuildSourceId   `json:"id"`

	// Image Present when the build source is currently image-based. Mutually exclusive with `git`.
	Image *BuildSourceImage `json:"image,omitempty"`
	Name  string            `json:"name"`

	// OwnerId ID of the workspace this build source belongs to.
	OwnerId string `json:"ownerId"`

	// ProjectId ID of the project this build source is scoped to, if any.
	ProjectId *string `json:"projectId,omitempty"`

	// ServiceLinks Services currently linked to this build source.
	ServiceLinks []BuildSourceServiceLink `json:"serviceLinks"`
	UpdatedAt    time.Time                `json:"updatedAt"`
}

// BuildSourceGit defines model for buildSourceGit.
type BuildSourceGit struct {
	BaseDir      *string `json:"baseDir,omitempty"`
	Branch       *string `json:"branch,omitempty"`
	BuildCommand *string `json:"buildCommand,omitempty"`

	// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
	BuildFilter    *BuildFilter `json:"buildFilter,omitempty"`
	DockerfilePath *string      `json:"dockerfilePath,omitempty"`

	// Region Defaults to "oregon"
	Region               *BuildSourceGitRegion `json:"region,omitempty"`
	RegistryCredentialId *string               `json:"registryCredentialId,omitempty"`
	RepoUrl              *string               `json:"repoUrl,omitempty"`
	RootDir              *string               `json:"rootDir,omitempty"`

	// Runtime Build runtime for the build source. Static sites are not supported for build sources.
	Runtime BuildSourceGitRuntime `json:"runtime"`
}

// BuildSourceGitRegion Defaults to "oregon"
type BuildSourceGitRegion string

// BuildSourceGitRuntime Build runtime for the build source. Static sites are not supported for build sources.
type BuildSourceGitRuntime string

// BuildSourceId defines model for buildSourceId.
type BuildSourceId = string

// BuildSourceImage defines model for buildSourceImage.
type BuildSourceImage struct {
	ImageUrl             string  `json:"imageUrl"`
	OwnerId              string  `json:"ownerId"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// BuildSourcePATCHGit defines model for buildSourcePATCHGit.
type BuildSourcePATCHGit struct {
	BaseDir      *string `json:"baseDir,omitempty"`
	Branch       *string `json:"branch,omitempty"`
	BuildCommand *string `json:"buildCommand,omitempty"`

	// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
	BuildFilter    *BuildFilter `json:"buildFilter,omitempty"`
	DockerfilePath *string      `json:"dockerfilePath,omitempty"`

	// Region Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
	Region *BuildSourcePATCHGitRegion `json:"region,omitempty"`

	// RegistryCredentialId Optional reference to the registry credential for this build. Omit the field to leave the stored credential unchanged; send an empty string to clear it.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
	RepoUrl              *string `json:"repoUrl,omitempty"`
	RootDir              *string `json:"rootDir,omitempty"`

	// Runtime Build runtime for the build source. Static sites are not supported for build sources.
	Runtime *BuildSourcePATCHGitRuntime `json:"runtime,omitempty"`
}

// BuildSourcePATCHGitRegion Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
type BuildSourcePATCHGitRegion string

// BuildSourcePATCHGitRuntime Build runtime for the build source. Static sites are not supported for build sources.
type BuildSourcePATCHGitRuntime string

// BuildSourcePATCHImage Patch shape for a build source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — a build source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
type BuildSourcePATCHImage struct {
	ImageUrl *string `json:"imageUrl,omitempty"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image. Omit the field to leave the stored credential unchanged; send an empty string to clear it.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// BuildSourcePATCHInput defines model for buildSourcePATCHInput.
type BuildSourcePATCHInput struct {
	Git *BuildSourcePATCHGit `json:"git,omitempty"`

	// Image Patch shape for a build source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — a build source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
	Image *BuildSourcePATCHImage `json:"image,omitempty"`
	Name  *string                `json:"name,omitempty"`
}

// BuildSourcePOSTInput defines model for buildSourcePOSTInput.
type BuildSourcePOSTInput struct {
	// EnvGroupIds IDs of env groups to link to the build source. Only valid for `git` sources; env groups must belong to the same workspace and must not be scoped to an environment.
	EnvGroupIds *[]string                      `json:"envGroupIds,omitempty"`
	EnvVars     *externalRef5.EnvVarInputArray `json:"envVars,omitempty"`
	Git         *BuildSourceGit                `json:"git,omitempty"`
	Image       *BuildSourceImage              `json:"image,omitempty"`
	Name        string                         `json:"name"`
	OwnerId     string                         `json:"ownerId"`
	ProjectId   *string                        `json:"projectId,omitempty"`

	// SecretFiles Secret files for the build source's build. Only valid for `git` sources.
	SecretFiles *[]externalRef5.SecretFileInput `json:"secretFiles,omitempty"`
	ServiceIds  *[]string                       `json:"serviceIds,omitempty"`
}

// BuildSourceServiceLink defines model for buildSourceServiceLink.
type BuildSourceServiceLink struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// BuildSourceWithCursor defines model for buildSourceWithCursor.
type BuildSourceWithCursor struct {
	BuildSource BuildSource `json:"buildSource"`
	Cursor      string      `json:"cursor"`
}

// Image Present when the build source is currently image-based. Mutually exclusive with `buildRun`.
type Image struct {
	SHA                  *string `json:"SHA,omitempty"`
	ImageUrl             *string `json:"imageUrl,omitempty"`
	ImageVersionId       *string `json:"imageVersionId,omitempty"`
	Ref                  *string `json:"ref,omitempty"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// BuildSourceIdParam defines model for buildSourceIdParam.
type BuildSourceIdParam = BuildSourceId
