---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wfv-d262g3atu6bs73fvh44g # workflow version ID
  # Update to your namespace
  namespace: own-d0v37akigahs739gebvg
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      render.com/workflow-version-id: wfv-d262g3atu6bs73fvh44g
  template:
    metadata:
      labels:
        render.com/durable-workflow: "1"
        render.com/workflow-role: worker
        render.com/workflow-service-id: wfl-d262f6sfu1ps73f98ho0
        render.com/workflow-version-id: wfv-d262g3atu6bs73fvh44g
    spec:
      imagePullSecrets:
      - name: gcr-docker-config
      containers:
      - command:
        - sh
        - -c
        - 'while true; do sleep 86400; done'
        image: gcr.io/render-devs/workflow-sdk-dev
        imagePullPolicy: Always
        name: dw-template
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - DAC_OVERRIDE
            - SETUID
            - SETGID
            - SYS_CHROOT
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            cpu: "1m"
            memory: "1Mi"
      schedulerName: render-custom-scheduler
      serviceAccountName: default
      terminationGracePeriodSeconds: 0
      nodeSelector:
        type: durable-workflows
      tolerations:
      - effect: NoSchedule
        key: render.com/node-type
        operator: Equal
        value: durable-workflows
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
    type: RollingUpdate
