# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.client.tests.test_render -> render.client.tests.test_render
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.client.tests.test_render", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.client.tests.test_render")
