// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see the readme at https://github.com/renderinc/public-api-schema

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

// Defines values for CronJobRunStatus.
const (
	CronJobRunStatusCanceled     CronJobRunStatus = "canceled"
	CronJobRunStatusPending      CronJobRunStatus = "pending"
	CronJobRunStatusSuccessful   CronJobRunStatus = "successful"
	CronJobRunStatusUnsuccessful CronJobRunStatus = "unsuccessful"
)

// Defines values for EventStatus.
const (
	EventStatusCanceled  EventStatus = "canceled"
	EventStatusFailed    EventStatus = "failed"
	EventStatusSucceeded EventStatus = "succeeded"
)

// CronJobRunStatus defines model for cronJobRunStatus.
type CronJobRunStatus string

// EventStatus defines model for eventStatus.
type EventStatus string
