# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.add_or_update_build_source_secret_file_body import (
    AddOrUpdateBuildSourceSecretFileBody as AddOrUpdateBuildSourceSecretFileBody,
    Any as Any,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
