# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.artifact_source_git_runtime import (
    ArtifactSourceGitRuntime as ArtifactSourceGitRuntime,
    Enum as Enum,
)
