# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.artifact_source_patch_git_region import (
    ArtifactSourcePATCHGitRegion as ArtifactSourcePATCHGitRegion,
    Enum as Enum,
)
