# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.artifact_source_service_link import (
    Any as Any,
    ArtifactSourceServiceLink as ArtifactSourceServiceLink,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
