# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.artifact_fetch_failed import (
    Any as Any,
    ArtifactFetchFailed as ArtifactFetchFailed,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
