# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.artifact_source_patch_git import (
    Any as Any,
    ArtifactSourcePATCHGit as ArtifactSourcePATCHGit,
    ArtifactSourcePATCHGitRegion as ArtifactSourcePATCHGitRegion,
    ArtifactSourcePATCHGitRuntime as ArtifactSourcePATCHGitRuntime,
    Mapping as Mapping,
    SchemasBuildFilter as SchemasBuildFilter,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
