# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.auto_deploy_disabled import (
    Any as Any,
    AutoDeployDisabled as AutoDeployDisabled,
    AutoDeployTrigger as AutoDeployTrigger,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
