# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.blueprint_detail import (
    Any as Any,
    BlueprintDetail as BlueprintDetail,
    Mapping as Mapping,
    ResourceRef as ResourceRef,
    Status as Status,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    isoparse as isoparse,
)
