# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.build_source_patch_git_runtime import (
    BuildSourcePATCHGitRuntime as BuildSourcePATCHGitRuntime,
    Enum as Enum,
)
