# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.cidr_block_and_description import (
    Any as Any,
    CidrBlockAndDescription as CidrBlockAndDescription,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
