# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.create_custom_domain_body import (
    Any as Any,
    CreateCustomDomainBody as CreateCustomDomainBody,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
