# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.credential_create_input import (
    Any as Any,
    CredentialCreateInput as CredentialCreateInput,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
