# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.cron_job_run_ended import (
    Any as Any,
    CronJobRunEnded as CronJobRunEnded,
    CronJobRunStatus as CronJobRunStatus,
    FailureReason as FailureReason,
    Mapping as Mapping,
    SchemasUser as SchemasUser,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
