# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.cron_job_details_patch import (
    Any as Any,
    CronJobDetailsPATCH as CronJobDetailsPATCH,
    DockerDetailsPATCH as DockerDetailsPATCH,
    Mapping as Mapping,
    NativeEnvironmentDetailsPATCH as NativeEnvironmentDetailsPATCH,
    PaidPlan as PaidPlan,
    ServiceRuntime as ServiceRuntime,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
