# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.dedicated_ip import (
    Any as Any,
    DedicatedIP as DedicatedIP,
    DedicatedIPStatus as DedicatedIPStatus,
    Mapping as Mapping,
    Region as Region,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    cast as cast,
    isoparse as isoparse,
)
