# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.disk_with_cursor import (
    Any as Any,
    DiskDetails as DiskDetails,
    DiskWithCursor as DiskWithCursor,
    Mapping as Mapping,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
