# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.docker_details_post import (
    Any as Any,
    DockerDetailsPOST as DockerDetailsPOST,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
