# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.edge_cache_enabled import (
    Any as Any,
    EdgeCacheEnabled as EdgeCacheEnabled,
    EdgeCacheTrigger as EdgeCacheTrigger,
    Mapping as Mapping,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
