# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.environment_resources_post_input import (
    Any as Any,
    EnvironmentResourcesPOSTInput as EnvironmentResourcesPOSTInput,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    cast as cast,
)
