# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.get_http_requests_aggregate_by import (
    Enum as Enum,
    GetHttpRequestsAggregateBy as GetHttpRequestsAggregateBy,
)
