# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.public_api.models.get_task_runs_completed_aggregate_by -> render.public_api.models.get_task_runs_completed_aggregate_by
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.public_api.models.get_task_runs_completed_aggregate_by", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.public_api.models.get_task_runs_completed_aggregate_by")
