# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.get_bandwidth_sources_response_200_data_item_labels_traffic_source import (
    Enum as Enum,
    GetBandwidthSourcesResponse200DataItemLabelsTrafficSource as GetBandwidthSourcesResponse200DataItemLabelsTrafficSource,
)
