# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.get_task_runs_completed_aggregate_by import (
    Enum as Enum,
    GetTaskRunsCompletedAggregateBy as GetTaskRunsCompletedAggregateBy,
)
