# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.job_run_ended import (
    Any as Any,
    FailureReason as FailureReason,
    JobRunEnded as JobRunEnded,
    JobStatus as JobStatus,
    Mapping as Mapping,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
