# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.label import (
    Any as Any,
    Label as Label,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
