# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.log_stream_resource_update import (
    Any as Any,
    LogStreamResourceUpdate as LogStreamResourceUpdate,
    LogStreamSetting as LogStreamSetting,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
