# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.maintenance_mode_uri_updated import (
    Any as Any,
    MaintenanceModeURIUpdated as MaintenanceModeURIUpdated,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
