# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.notification_setting import (
    Any as Any,
    Mapping as Mapping,
    NotificationSetting as NotificationSetting,
    NotifySettingV2 as NotifySettingV2,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
