# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.object_metadata import (
    Any as Any,
    Mapping as Mapping,
    ObjectMetadata as ObjectMetadata,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    isoparse as isoparse,
)
