# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.outbound_ips import (
    Any as Any,
    Mapping as Mapping,
    OutboundIps as OutboundIps,
    OutboundIpsType as OutboundIpsType,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    cast as cast,
)
