# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.public_api.models.patch_route_response_200 -> render.public_api.models.patch_route_response_200
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.public_api.models.patch_route_response_200", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.public_api.models.patch_route_response_200")
