# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.pipeline_minutes_exhausted import (
    Any as Any,
    BuildDeployTrigger as BuildDeployTrigger,
    Mapping as Mapping,
    PipelineMinutesExhausted as PipelineMinutesExhausted,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
