# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.postgres_cluster_leader_changed import (
    Any as Any,
    Mapping as Mapping,
    PostgresClusterLeaderChanged as PostgresClusterLeaderChanged,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
