# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.postgres_pitr_checkpoint_completed import (
    Any as Any,
    Mapping as Mapping,
    PostgresPITRCheckpointCompleted as PostgresPITRCheckpointCompleted,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
