# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.project import (
    Any as Any,
    Mapping as Mapping,
    Owner as Owner,
    Project as Project,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    cast as cast,
    isoparse as isoparse,
)
