# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.pull_request_previews_enabled import (
    Enum as Enum,
    PullRequestPreviewsEnabled as PullRequestPreviewsEnabled,
)
