# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.put_object_output import (
    Any as Any,
    Mapping as Mapping,
    PutObjectOutput as PutObjectOutput,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    isoparse as isoparse,
)
