# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.registry_credential_registry import (
    Enum as Enum,
    RegistryCredentialRegistry as RegistryCredentialRegistry,
)
