# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.registry_credential_summary import (
    Any as Any,
    Mapping as Mapping,
    RegistryCredentialSummary as RegistryCredentialSummary,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
