# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.registry_credential import (
    Any as Any,
    Mapping as Mapping,
    RegistryCredential as RegistryCredential,
    RegistryCredentialRegistry as RegistryCredentialRegistry,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
    isoparse as isoparse,
)
