# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.resource_log_stream_setting import (
    Any as Any,
    LogStreamSetting as LogStreamSetting,
    Mapping as Mapping,
    ResourceLogStreamSetting as ResourceLogStreamSetting,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
