# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.route_put import (
    Any as Any,
    Mapping as Mapping,
    RoutePut as RoutePut,
    RouteType as RouteType,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
