# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.sandbox_network_policy_default import (
    Enum as Enum,
    SandboxNetworkPolicyDefault as SandboxNetworkPolicyDefault,
)
