# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.sandbox_egress_rule_protocol import (
    Enum as Enum,
    SandboxEgressRuleProtocol as SandboxEgressRuleProtocol,
)
