# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.service_disk_usage_recovered import (
    Any as Any,
    Mapping as Mapping,
    ServiceDiskUsageRecovered as ServiceDiskUsageRecovered,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
