# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.setup_postgres_replication_response_201 import (
    Any as Any,
    Mapping as Mapping,
    SetupPostgresReplicationResponse201 as SetupPostgresReplicationResponse201,
    T as T,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
