# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.task_data_type_1 import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TaskDataType1 as TaskDataType1,
    TypeVar as TypeVar,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
