# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.update_workspace_member_body import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TeamMemberRole as TeamMemberRole,
    TypeVar as TypeVar,
    UpdateWorkspaceMemberBody as UpdateWorkspaceMemberBody,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
