# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.update_env_group_secret_file_body import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    UpdateEnvGroupSecretFileBody as UpdateEnvGroupSecretFileBody,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
