# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.update_registry_credential_body import (
    Any as Any,
    Mapping as Mapping,
    RegistryCredentialRegistry as RegistryCredentialRegistry,
    T as T,
    TypeVar as TypeVar,
    UpdateRegistryCredentialBody as UpdateRegistryCredentialBody,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
