# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.webhook_patch_input import (
    Any as Any,
    EventType as EventType,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    UNSET as UNSET,
    Union as Union,
    Unset as Unset,
    WebhookPATCHInput as WebhookPATCHInput,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
