# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.webhook_post_input import (
    Any as Any,
    EventType as EventType,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    WebhookPOSTInput as WebhookPOSTInput,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
