# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.webhook_event_with_cursor import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    WebhookEvent as WebhookEvent,
    WebhookEventWithCursor as WebhookEventWithCursor,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
