# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.workflow_with_cursor import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TYPE_CHECKING as TYPE_CHECKING,
    TypeVar as TypeVar,
    Workflow as Workflow,
    WorkflowWithCursor as WorkflowWithCursor,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
