# Generated by scripts/generate_mirror.py - do not edit.
from render.public_api.models.zero_downtime_redeploy_ended import (
    Any as Any,
    Mapping as Mapping,
    T as T,
    TypeVar as TypeVar,
    ZeroDowntimeRedeployEnded as ZeroDowntimeRedeployEnded,
    _attrs_define as _attrs_define,
    _attrs_field as _attrs_field,
)
