# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.client.types -> render.client.types
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.client.types", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.client.types")
