# Generated by scripts/generate_mirror.py - do not edit.
from render.client.types import (
    Any as Any,
    CursorParam as CursorParam,
    LimitParam as LimitParam,
    ListTaskRunsParams as ListTaskRunsParams,
    OwnerIDParam as OwnerIDParam,
    TaskData as TaskData,
    TaskRun as TaskRun,
    TaskRunDetails as TaskRunDetails,
    TaskRunStatus as TaskRunStatus,
    TaskRunStatusValues as TaskRunStatusValues,
    TaskSlug as TaskSlug,
    _TaskRun as _TaskRun,
    _TaskRunDetails as _TaskRunDetails,
    _TaskRunStatus as _TaskRunStatus,
)
