# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.render -> render.render
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.render", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.render")
