# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.experimental.key_value.compare -> render.experimental.key_value.compare
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.experimental.key_value.compare", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.experimental.key_value.compare")
