# Generated by scripts/generate_mirror.py - do not edit.
from render.workflows.tests.test_version import (
    test_version_matches_distribution_metadata as test_version_matches_distribution_metadata,
)
