# Generated by scripts/generate_mirror.py - do not edit.
from render.workflows.tests.test_lazy_imports import (
    _ALLOWED_ON_WORKER_PATH as _ALLOWED_ON_WORKER_PATH,
    _FORBIDDEN_ON_WORKER_PATH as _FORBIDDEN_ON_WORKER_PATH,
    _modules_loaded_by as _modules_loaded_by,
    test_lazy_attrs_still_resolve_when_explicitly_accessed as test_lazy_attrs_still_resolve_when_explicitly_accessed,
    test_worker_path_does_not_load_rest_or_experimental_modules as test_worker_path_does_not_load_rest_or_experimental_modules,
)
