# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias package: render_sdk.public_api.api.dedicated_i_ps -> render.public_api.api.dedicated_i_ps
#
# This package keeps its own sys.modules identity (self-aliasing would point
# __path__ at the real directory and re-execute real sources under render_sdk.public_api.api.dedicated_i_ps
# names) but forwards ALL attribute access to the real package, so every
# attribute reachable through it is the real object.
import importlib
import sys
import types

_real = importlib.import_module("render.public_api.api.dedicated_i_ps")

__doc__ = _real.__doc__
__all__ = []


class _AliasPackage(types.ModuleType):
    def __getattr__(self, name):
        return getattr(_real, name)

    def __dir__(self):
        return dir(_real)

    def __setattr__(self, name, value):
        # After loading a child module the import system binds it onto this
        # package (setattr(parent, "task", <module>)). The real package may
        # shadow that name with a same-named attribute (render.workflows.task
        # is the task decorator, not the submodule); mirroring must not let
        # the child binding change what the attribute resolves to. Drop any
        # module binding that diverges from the real package's attribute.
        if (
            isinstance(value, types.ModuleType)
            and getattr(_real, name, value) is not value
        ):
            return
        super().__setattr__(name, value)


sys.modules[__name__].__class__ = _AliasPackage
