// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

// Defines values for AutoDeployTrigger.
const (
	ChecksPass AutoDeployTrigger = "checksPass"
	Commit     AutoDeployTrigger = "commit"
	Off        AutoDeployTrigger = "off"
)

// Valid indicates whether the value is a known member of the AutoDeployTrigger enum.
func (e AutoDeployTrigger) Valid() bool {
	switch e {
	case ChecksPass:
		return true
	case Commit:
		return true
	case Off:
		return true
	default:
		return false
	}
}

// AutoDeployTrigger Controls autodeploy behavior. commit deploys when a commit is pushed to a branch. checksPass waits for the branch to be green.
type AutoDeployTrigger string
