# Generated by scripts/generate_mirror.py - do not edit.
from render.experimental.object.tests.test_e2e import (
    RenderAsync as RenderAsync,
    TestObjectClientE2E as TestObjectClientE2E,
    TestObjectClientPagination as TestObjectClientPagination,
    object_storage_crud_check as object_storage_crud_check,
    owner_id as owner_id,
    pytestmark as pytestmark,
    region as region,
    render as render,
)
