# Generated by scripts/generate_mirror.py - do not edit.
from render.experimental.object.tests.test_client import (
    BytesIO as BytesIO,
    ObjectClient as ObjectClient,
    SimpleNamespace as SimpleNamespace,
    TestDefaultScopeResolution as TestDefaultScopeResolution,
    TestEnvVarResolution as TestEnvVarResolution,
    UploadResponse as UploadResponse,
    datetime as datetime,
    test_put_accepts_async_byte_iterators as test_put_accepts_async_byte_iterators,
    test_put_streams_binary_file_objects as test_put_streams_binary_file_objects,
)
