from enum import Enum


class EventType(str, Enum):
    AUTOSCALING_CONFIG_CHANGED = "autoscaling_config_changed"
    AUTOSCALING_ENDED = "autoscaling_ended"
    AUTOSCALING_STARTED = "autoscaling_started"
    BRANCH_DELETED = "branch_deleted"
    BUILD_ENDED = "build_ended"
    BUILD_STARTED = "build_started"
    COMMIT_IGNORED = "commit_ignored"
    CRON_JOB_RUN_ENDED = "cron_job_run_ended"
    CRON_JOB_RUN_STARTED = "cron_job_run_started"
    DEPLOY_ENDED = "deploy_ended"
    DEPLOY_STARTED = "deploy_started"
    DISK_CREATED = "disk_created"
    DISK_DELETED = "disk_deleted"
    DISK_UPDATED = "disk_updated"
    EDGE_CACHE_DISABLED = "edge_cache_disabled"
    EDGE_CACHE_ENABLED = "edge_cache_enabled"
    EDGE_CACHE_PURGED = "edge_cache_purged"
    IMAGE_PULL_FAILED = "image_pull_failed"
    INSTANCE_COUNT_CHANGED = "instance_count_changed"
    JOB_RUN_ENDED = "job_run_ended"
    KEY_VALUE_AVAILABLE = "key_value_available"
    KEY_VALUE_CONFIG_RESTART = "key_value_config_restart"
    KEY_VALUE_UNHEALTHY = "key_value_unhealthy"
    MAINTENANCE_ENDED = "maintenance_ended"
    MAINTENANCE_MODE_ENABLED = "maintenance_mode_enabled"
    MAINTENANCE_MODE_URI_UPDATED = "maintenance_mode_uri_updated"
    MAINTENANCE_STARTED = "maintenance_started"
    PIPELINE_MINUTES_EXHAUSTED = "pipeline_minutes_exhausted"
    PLAN_CHANGED = "plan_changed"
    POSTGRES_AVAILABLE = "postgres_available"
    POSTGRES_BACKUP_COMPLETED = "postgres_backup_completed"
    POSTGRES_BACKUP_FAILED = "postgres_backup_failed"
    POSTGRES_BACKUP_STARTED = "postgres_backup_started"
    POSTGRES_CLUSTER_LEADER_CHANGED = "postgres_cluster_leader_changed"
    POSTGRES_CREATED = "postgres_created"
    POSTGRES_DISK_SIZE_CHANGED = "postgres_disk_size_changed"
    POSTGRES_HA_STATUS_CHANGED = "postgres_ha_status_changed"
    POSTGRES_PITR_CHECKPOINT_COMPLETED = "postgres_pitr_checkpoint_completed"
    POSTGRES_PITR_CHECKPOINT_FAILED = "postgres_pitr_checkpoint_failed"
    POSTGRES_PITR_CHECKPOINT_STARTED = "postgres_pitr_checkpoint_started"
    POSTGRES_READ_REPLICAS_CHANGED = "postgres_read_replicas_changed"
    POSTGRES_READ_REPLICA_STALE = "postgres_read_replica_stale"
    POSTGRES_RESTARTED = "postgres_restarted"
    POSTGRES_RESTORE_FAILED = "postgres_restore_failed"
    POSTGRES_RESTORE_SUCCEEDED = "postgres_restore_succeeded"
    POSTGRES_UNAVAILABLE = "postgres_unavailable"
    POSTGRES_UPGRADE_FAILED = "postgres_upgrade_failed"
    POSTGRES_UPGRADE_STARTED = "postgres_upgrade_started"
    POSTGRES_UPGRADE_SUCCEEDED = "postgres_upgrade_succeeded"
    POSTGRES_WAL_ARCHIVE_FAILED = "postgres_wal_archive_failed"
    PRE_DEPLOY_ENDED = "pre_deploy_ended"
    PRE_DEPLOY_STARTED = "pre_deploy_started"
    SERVER_AVAILABLE = "server_available"
    SERVER_FAILED = "server_failed"
    SERVER_HARDWARE_FAILURE = "server_hardware_failure"
    SERVER_RESTARTED = "server_restarted"
    SERVER_UNHEALTHY = "server_unhealthy"
    SERVICE_RESUMED = "service_resumed"
    SERVICE_SUSPENDED = "service_suspended"
    ZERO_DOWNTIME_REDEPLOY_ENDED = "zero_downtime_redeploy_ended"
    ZERO_DOWNTIME_REDEPLOY_STARTED = "zero_downtime_redeploy_started"

    def __str__(self) -> str:
        return str(self.value)
