from enum import Enum


class ServiceEventType(str, Enum):
    AUTOSCALING_CONFIG_CHANGED = "autoscaling_config_changed"
    AUTOSCALING_ENDED = "autoscaling_ended"
    AUTOSCALING_STARTED = "autoscaling_started"
    BRANCH_DELETED = "branch_deleted"
    BUILD_ENDED = "build_ended"
    BUILD_STARTED = "build_started"
    COMMIT_IGNORED = "commit_ignored"
    CRON_JOB_RUN_ENDED = "cron_job_run_ended"
    CRON_JOB_RUN_STARTED = "cron_job_run_started"
    DEPLOY_ENDED = "deploy_ended"
    DEPLOY_STARTED = "deploy_started"
    DISK_CREATED = "disk_created"
    DISK_DELETED = "disk_deleted"
    DISK_UPDATED = "disk_updated"
    IMAGE_PULL_FAILED = "image_pull_failed"
    INITIAL_DEPLOY_HOOK_ENDED = "initial_deploy_hook_ended"
    INITIAL_DEPLOY_HOOK_STARTED = "initial_deploy_hook_started"
    INSTANCE_COUNT_CHANGED = "instance_count_changed"
    JOB_RUN_ENDED = "job_run_ended"
    MAINTENANCE_ENDED = "maintenance_ended"
    MAINTENANCE_MODE_ENABLED = "maintenance_mode_enabled"
    MAINTENANCE_MODE_URI_UPDATED = "maintenance_mode_uri_updated"
    MAINTENANCE_STARTED = "maintenance_started"
    PIPELINE_MINUTES_EXHAUSTED = "pipeline_minutes_exhausted"
    PLAN_CHANGED = "plan_changed"
    PRE_DEPLOY_ENDED = "pre_deploy_ended"
    PRE_DEPLOY_STARTED = "pre_deploy_started"
    SERVER_AVAILABLE = "server_available"
    SERVER_FAILED = "server_failed"
    SERVER_HARDWARE_FAILURE = "server_hardware_failure"
    SERVER_RESTARTED = "server_restarted"
    SERVER_UNHEALTHY = "server_unhealthy"
    SERVICE_RESUMED = "service_resumed"
    SERVICE_SUSPENDED = "service_suspended"
    SUSPENDER_ADDED = "suspender_added"
    SUSPENDER_REMOVED = "suspender_removed"
    ZERO_DOWNTIME_REDEPLOY_ENDED = "zero_downtime_redeploy_ended"
    ZERO_DOWNTIME_REDEPLOY_STARTED = "zero_downtime_redeploy_started"

    def __str__(self) -> str:
        return str(self.value)
