// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CallbackRequestStatus.
const (
	CallbackRequestStatusComplete CallbackRequestStatus = "complete"
	CallbackRequestStatusSubtask  CallbackRequestStatus = "subtask"
)

// CallbackRequest defines model for CallbackRequest.
type CallbackRequest struct {
	Complete *TaskComplete         `json:"complete,omitempty"`
	Name     string                `json:"name"`
	Status   CallbackRequestStatus `json:"status"`
	Subtask  *Subtask              `json:"subtask,omitempty"`
	TaskId   string                `json:"task_id"`
}

// CallbackRequestStatus defines model for CallbackRequest.Status.
type CallbackRequestStatus string

// CallbackResponse defines model for CallbackResponse.
type CallbackResponse struct {
	TaskId *string `json:"task_id,omitempty"`
}

// Subtask defines model for Subtask.
type Subtask struct {
	Input interface{} `json:"input"`
	Name  string      `json:"name"`
}

// TaskComplete defines model for TaskComplete.
type TaskComplete struct {
	Result interface{} `json:"result"`
}

// PostCallbackParams defines parameters for PostCallback.
type PostCallbackParams struct {
	Token string `form:"token" json:"token"`
}

// PostCallbackJSONRequestBody defines body for PostCallback for application/json ContentType.
type PostCallbackJSONRequestBody = CallbackRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCallbackWithBody request with any body
	PostCallbackWithBody(ctx context.Context, params *PostCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCallback(ctx context.Context, params *PostCallbackParams, body PostCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCallbackWithBody(ctx context.Context, params *PostCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCallbackRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCallback(ctx context.Context, params *PostCallbackParams, body PostCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCallbackRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCallbackRequest calls the generic PostCallback builder with application/json body
func NewPostCallbackRequest(server string, params *PostCallbackParams, body PostCallbackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCallbackRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCallbackRequestWithBody generates requests for PostCallback with any type of body
func NewPostCallbackRequestWithBody(server string, params *PostCallbackParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/callback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "token", runtime.ParamLocationQuery, params.Token); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCallbackWithBodyWithResponse request with any body
	PostCallbackWithBodyWithResponse(ctx context.Context, params *PostCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCallbackResponse, error)

	PostCallbackWithResponse(ctx context.Context, params *PostCallbackParams, body PostCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCallbackResponse, error)
}

type PostCallbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CallbackResponse
}

// Status returns HTTPResponse.Status
func (r PostCallbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCallbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCallbackWithBodyWithResponse request with arbitrary body returning *PostCallbackResponse
func (c *ClientWithResponses) PostCallbackWithBodyWithResponse(ctx context.Context, params *PostCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCallbackResponse, error) {
	rsp, err := c.PostCallbackWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCallbackResponse(rsp)
}

func (c *ClientWithResponses) PostCallbackWithResponse(ctx context.Context, params *PostCallbackParams, body PostCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCallbackResponse, error) {
	rsp, err := c.PostCallback(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCallbackResponse(rsp)
}

// ParsePostCallbackResponse parses an HTTP response from a PostCallbackWithResponse call
func ParsePostCallbackResponse(rsp *http.Response) (*PostCallbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCallbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CallbackResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
