# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.workflows._callback_models -> render.workflows._callback_models
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.workflows._callback_models", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.workflows._callback_models")
