# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.workflows.cli -> render.workflows.cli
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.workflows.cli", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.workflows.cli")
