[tox]
envlist = py310,py311,py312,py313,py314,format,lint
isolated_build = true

[testenv]
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync
commands =
    uv run pytest {posargs}

[testenv:format]
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync
commands =
    uv run black --check --diff .
    uv run isort --check-only --diff .

[testenv:format-fix]
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync
commands =
    uv run black .
    uv run isort .

[testenv:lint]
skip_install = true
allowlist_externals = uv, find, bash
commands_pre =
    uv sync
commands =
    uv run ruff check .
    bash -c 'find ./render_sdk -path "./render_sdk/public_api" -prune -o -path "./render_sdk/workflows/callback_api" -prune -o -name "*.py" -print | xargs uv run mypy'

[testenv:lint-fix]
skip_install = true
allowlist_externals = uv, bash
commands_pre =
    uv sync
commands =
    uv run ruff check --fix .

[testenv:e2e]
skip_install = true
allowlist_externals = uv
passenv =
    RENDER_API_KEY
    RENDER_BASE_URL
    RENDER_E2E_OWNER_ID
    RENDER_E2E_PAGINATION_OWNER_ID
    RENDER_E2E_REGION
commands_pre =
    uv sync
commands =
    uv run pytest -m e2e -v {posargs}

[testenv:all]
commands =
    {[testenv:format]commands}
    {[testenv:lint]commands}
    {[testenv]commands}
