[tox]
envlist = py39,py310,py311,py312,py313,py314,format,lint
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
    pytest-asyncio
    pytest-mock
commands = pytest {posargs}

[testenv:format]
deps =
    black
    isort
commands =
    black --check --diff .
    isort --check-only --diff .

[testenv:format-fix]
deps =
    black
    isort
commands =
    black .
    isort .

[testenv:lint]
deps =
    ruff
    mypy
commands =
    ruff check .
    mypy .

[testenv:lint-fix]
deps =
    ruff
commands =
    ruff check --fix .

[testenv:all]
deps =
    {[testenv]deps}
    {[testenv:format]deps}
    {[testenv:lint]deps}
commands =
    {[testenv:format]commands}
    {[testenv:lint]commands}
    {[testenv]commands}
