# Generated by scripts/generate_mirror.py - do not edit.
from render.experimental.object.e2e_helpers import (
    ObjectClient as ObjectClient,
    RETRY_ATTEMPTS as RETRY_ATTEMPTS,
    RETRY_INTERVAL_S as RETRY_INTERVAL_S,
    RenderError as RenderError,
    object_storage_crud_check as object_storage_crud_check,
)
