// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for SandboxFileEntryType.
const (
	Directory SandboxFileEntryType = "directory"
	File      SandboxFileEntryType = "file"
	Symlink   SandboxFileEntryType = "symlink"
)

// Valid indicates whether the value is a known member of the SandboxFileEntryType enum.
func (e SandboxFileEntryType) Valid() bool {
	switch e {
	case Directory:
		return true
	case File:
		return true
	case Symlink:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLifecycleEventType.
const (
	SandboxLifecycleEventTypeCreating   SandboxLifecycleEventType = "creating"
	SandboxLifecycleEventTypeErrored    SandboxLifecycleEventType = "errored"
	SandboxLifecycleEventTypeResuming   SandboxLifecycleEventType = "resuming"
	SandboxLifecycleEventTypeRunning    SandboxLifecycleEventType = "running"
	SandboxLifecycleEventTypeSuspended  SandboxLifecycleEventType = "suspended"
	SandboxLifecycleEventTypeTerminated SandboxLifecycleEventType = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxLifecycleEventType enum.
func (e SandboxLifecycleEventType) Valid() bool {
	switch e {
	case SandboxLifecycleEventTypeCreating:
		return true
	case SandboxLifecycleEventTypeErrored:
		return true
	case SandboxLifecycleEventTypeResuming:
		return true
	case SandboxLifecycleEventTypeRunning:
		return true
	case SandboxLifecycleEventTypeSuspended:
		return true
	case SandboxLifecycleEventTypeTerminated:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLogEventStream.
const (
	Stderr SandboxLogEventStream = "stderr"
	Stdout SandboxLogEventStream = "stdout"
)

// Valid indicates whether the value is a known member of the SandboxLogEventStream enum.
func (e SandboxLogEventStream) Valid() bool {
	switch e {
	case Stderr:
		return true
	case Stdout:
		return true
	default:
		return false
	}
}

// Defines values for SandboxNetworkPolicyDefault.
const (
	AllowAll SandboxNetworkPolicyDefault = "allow-all"
	DenyAll  SandboxNetworkPolicyDefault = "deny-all"
)

// Valid indicates whether the value is a known member of the SandboxNetworkPolicyDefault enum.
func (e SandboxNetworkPolicyDefault) Valid() bool {
	switch e {
	case AllowAll:
		return true
	case DenyAll:
		return true
	default:
		return false
	}
}

// Defines values for SandboxPlan.
const (
	Pro      SandboxPlan = "pro"
	Standard SandboxPlan = "standard"
	Starter  SandboxPlan = "starter"
)

// Valid indicates whether the value is a known member of the SandboxPlan enum.
func (e SandboxPlan) Valid() bool {
	switch e {
	case Pro:
		return true
	case Standard:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for SandboxStatus.
const (
	SandboxStatusCreating   SandboxStatus = "creating"
	SandboxStatusErrored    SandboxStatus = "errored"
	SandboxStatusResuming   SandboxStatus = "resuming"
	SandboxStatusRunning    SandboxStatus = "running"
	SandboxStatusSuspended  SandboxStatus = "suspended"
	SandboxStatusTerminated SandboxStatus = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxStatus enum.
func (e SandboxStatus) Valid() bool {
	switch e {
	case SandboxStatusCreating:
		return true
	case SandboxStatusErrored:
		return true
	case SandboxStatusResuming:
		return true
	case SandboxStatusRunning:
		return true
	case SandboxStatusSuspended:
		return true
	case SandboxStatusTerminated:
		return true
	default:
		return false
	}
}

// Sandbox defines model for sandbox.
type Sandbox struct {
	// CreatedAt Example: 2026-04-01T18:30:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: sbx-cph1rs3idesc73a2b2mg
	Id            SandboxId            `json:"id"`
	NetworkPolicy SandboxNetworkPolicy `json:"networkPolicy"`

	// Plan Compute plan. Sizing matches Workflow plans of the same name.
	Plan SandboxPlan `json:"plan"`

	// Region Region the sandbox is running in.
	//
	// Example: oregon
	Region string        `json:"region"`
	Status SandboxStatus `json:"status"`

	// TerminatedAt When the sandbox was terminated, or null.
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds.
	//
	// Example: 7200
	TimeoutSeconds int `json:"timeoutSeconds"`
}

// SandboxConnectResponse A minted connect token and the sandbox-proxy endpoint to invoke with it.
// Send the request (and body, where the operation takes one) to `uri`
// using `method`, with `token` as a bearer credential.
type SandboxConnectResponse struct {
	// ExecutionId Identifier for this execution.
	//
	// Example: exe-abc123
	ExecutionId string `json:"executionId"`

	// ExpiresAt When `token` stops being valid. Start the run before this time.
	//
	// Example: 2026-07-10T12:00:00Z
	ExpiresAt time.Time `json:"expiresAt"`

	// Method HTTP method to use against `uri`.
	//
	// Example: POST
	Method string `json:"method"`

	// Token Short-lived bearer token authorizing exactly this operation against the sandbox.
	Token string `json:"token"`

	// Uri The sandbox-proxy endpoint to invoke.
	//
	// Example: https://sbx-abc123.oregon.sandbox.onrender.com/runs/stream
	Uri string `json:"uri"`
}

// SandboxDirectoryListing Directory listing response.
type SandboxDirectoryListing struct {
	Entries []SandboxFileEntry `json:"entries"`

	// Path The absolute path that was listed.
	//
	// Example: /app
	Path string `json:"path"`
}

// SandboxFileEntry A file or directory entry in a sandbox filesystem listing.
type SandboxFileEntry struct {
	// ModifiedAt Last-modified timestamp.
	ModifiedAt time.Time `json:"modifiedAt"`

	// Name File or directory name (basename, not full path).
	//
	// Example: main.py
	Name string `json:"name"`

	// Size Size in bytes. 0 for directories and symlinks.
	//
	// Example: 2048
	Size int `json:"size"`

	// Target Symlink target path. Present only when type is `symlink`.
	Target *string `json:"target,omitempty"`

	// Type Entry type.
	Type SandboxFileEntryType `json:"type"`
}

// SandboxFileEntryType Entry type.
type SandboxFileEntryType string

// SandboxGroup defines model for sandboxGroup.
type SandboxGroup struct {
	// CreatedAt Example: 2026-07-02T18:30:00Z
	CreatedAt time.Time `json:"createdAt"`

	// EnvironmentId Environment this group is bound to.
	EnvironmentId *string `json:"environmentId,omitempty"`

	// Id Example: sbg-cph1rs3idesc73a2b2mg
	Id SandboxGroupId `json:"id"`

	// IsDefault Whether this is the workspace's default group. Exactly one group per workspace is the default.
	IsDefault bool `json:"isDefault"`

	// Name Human-friendly name for the group.
	//
	// Example: Default
	Name string `json:"name"`

	// OwnerId The ID of the workspace this group belongs to.
	//
	// Example: tea-cph1rs3idesc73a2b2mg
	OwnerId string `json:"ownerId"`

	// Region Render region the group operates in.
	//
	// Example: oregon
	Region string `json:"region"`

	// UpdatedAt Example: 2026-07-02T18:30:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// SandboxGroupId Example: sbg-cph1rs3idesc73a2b2mg
type SandboxGroupId = string

// SandboxId Example: sbx-cph1rs3idesc73a2b2mg
type SandboxId = string

// SandboxLifecycleEvent A lifecycle event from the sandbox logs stream.
type SandboxLifecycleEvent struct {
	At   time.Time                 `json:"at"`
	Type SandboxLifecycleEventType `json:"type"`
}

// SandboxLifecycleEventType defines model for SandboxLifecycleEvent.Type.
type SandboxLifecycleEventType string

// SandboxLogEvent A log event from the sandbox logs stream.
type SandboxLogEvent struct {
	At time.Time `json:"at"`

	// Data Output chunk.
	Data string `json:"data"`

	// ExecId Groups output by command for the event timeline. Absent for system-level output (container startup, OOM, etc.).
	//
	// Example: exec-abc123
	ExecId *string               `json:"execId,omitempty"`
	Stream SandboxLogEventStream `json:"stream"`
}

// SandboxLogEventStream defines model for SandboxLogEvent.Stream.
type SandboxLogEventStream string

// SandboxNetworkPolicy defines model for sandboxNetworkPolicy.
type SandboxNetworkPolicy struct {
	// Default Default action for outbound traffic.
	Default SandboxNetworkPolicyDefault `json:"default"`
}

// SandboxNetworkPolicyDefault Default action for outbound traffic.
type SandboxNetworkPolicyDefault string

// SandboxPOST defines model for sandboxPOST.
type SandboxPOST struct {
	// Env Inline environment variables injected into the sandbox at creation.
	Env           *map[string]string    `json:"env,omitempty"`
	NetworkPolicy *SandboxNetworkPolicy `json:"networkPolicy,omitempty"`

	// OwnerId The ID of the workspace the sandbox belongs to.
	OwnerId string       `json:"ownerId"`
	Plan    *SandboxPlan `json:"plan,omitempty"`

	// Region Render region. Defaults to the workspace default.
	Region *string `json:"region,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds. Sandbox is terminated when reached.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// SandboxPlan Compute plan. Sizing matches Workflow plans of the same name.
type SandboxPlan string

// SandboxStatus defines model for sandboxStatus.
type SandboxStatus string
