# Generated by scripts/generate_mirror.py - do not edit.
from render.experimental.sandbox.tests.test_tar import (
    CHUNK_SIZE as CHUNK_SIZE,
    Path as Path,
    _members as _members,
    _tree as _tree,
    aiter_tar_gzip as aiter_tar_gzip,
    iter_tar_gzip as iter_tar_gzip,
    test_a_symlinked_root_is_followed as test_a_symlinked_root_is_followed,
    test_abandoning_the_archive_stops_the_producer as test_abandoning_the_archive_stops_the_producer,
    test_async_archive_matches_the_sync_one as test_async_archive_matches_the_sync_one,
    test_cancelling_mid_archive_stops_the_producer as test_cancelling_mid_archive_stops_the_producer,
    test_entries_are_relative_and_the_root_is_not_emitted as test_entries_are_relative_and_the_root_is_not_emitted,
    test_hardlinks_are_stored_as_regular_files as test_hardlinks_are_stored_as_regular_files,
    test_multi_chunk_archive_round_trips as test_multi_chunk_archive_round_trips,
    test_producer_failure_reaches_the_consumer as test_producer_failure_reaches_the_consumer,
    test_special_files_are_skipped as test_special_files_are_skipped,
    test_symlinks_are_stored_not_followed as test_symlinks_are_stored_not_followed,
)
