# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.public_api.api.sandboxes.list_sandbox_groups -> render.public_api.api.sandboxes.list_sandbox_groups
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.public_api.api.sandboxes.list_sandbox_groups", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.public_api.api.sandboxes.list_sandbox_groups")
