# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.experimental.key_value.tests.test_provider -> render.experimental.key_value.tests.test_provider
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.experimental.key_value.tests.test_provider", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.experimental.key_value.tests.test_provider")
