// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see the readme at https://github.com/renderinc/public-api-schema

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"time"
)

// GetObjectOutput defines model for getObjectOutput.
type GetObjectOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	ExpiresAt time.Time `json:"expiresAt"`

	// Url Presigned URL for downloading the object
	Url string `json:"url"`
}

// ObjectMetadata defines model for objectMetadata.
type ObjectMetadata struct {
	// Key The object's key
	Key string `json:"key"`

	// LastModified When the object was last modified (ISO 8601)
	LastModified time.Time `json:"lastModified"`

	// SizeBytes Size of the object in bytes
	SizeBytes int64 `json:"sizeBytes"`
}

// ObjectWithCursor defines model for objectWithCursor.
type ObjectWithCursor struct {
	Cursor string         `json:"cursor"`
	Object ObjectMetadata `json:"object"`
}

// PutObjectInput defines model for putObjectInput.
type PutObjectInput struct {
	// SizeBytes The size of the object in bytes.
	SizeBytes int64 `json:"sizeBytes"`
}

// PutObjectOutput defines model for putObjectOutput.
type PutObjectOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	ExpiresAt time.Time `json:"expiresAt"`

	// MaxSizeBytes The maximum size of the object in bytes
	MaxSizeBytes int64 `json:"maxSizeBytes"`

	// Url Presigned URL for uploading the object
	Url string `json:"url"`
}

// ObjectKeyPathParam defines model for objectKeyPathParam.
type ObjectKeyPathParam = string
