# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.public_api.api.postgres.create_postgres_export -> render.public_api.api.postgres.create_postgres_export
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.public_api.api.postgres.create_postgres_export", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.public_api.api.postgres.create_postgres_export")
