# Generated by scripts/generate_mirror.py - do not edit.
# Compatibility alias: render_sdk.public_api.api.postgres.list_postgres_users -> render.public_api.api.postgres.list_postgres_users
if __name__ == "__main__":
    import runpy

    runpy.run_module("render.public_api.api.postgres.list_postgres_users", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("render.public_api.api.postgres.list_postgres_users")
