#!/usr/bin/env python3
"""Generate the `render_sdk` compatibility mirror of the `render` package.

For every module `render.x.y` in the real SDK (../python/render), emit:

- `render_sdk/x/y.py` — a runtime shim. Leaf modules alias themselves to the
  real module in sys.modules (so `render_sdk.x.y is render.x.y`) and delegate
  `python -m render_sdk.x.y` to the real module via runpy. Package __init__
  modules keep their own identity (self-replacement would point the package
  __path__ at the real directory and re-execute real sources under render_sdk
  names) and instead forward attribute access to the real package.
- `render_sdk/x/y.pyi` — a stub with explicit `name as name` re-exports of the
  real module's top-level bindings, so mypy/pyright resolve `render_sdk.*` to
  the exact `render.*` types, including under --no-implicit-reexport/--strict.
  Stubs take precedence over the runtime shims for type checkers, which keeps
  the real package's lazy-import behavior intact at runtime.

Also mirrors py.typed markers and syncs the metapackage version and
`render==X.Y.Z` pins in pyproject.toml to the SDK's version.

Usage:
    python scripts/generate_mirror.py          # (Re)generate the mirror
    python scripts/generate_mirror.py --check  # Verify mirror is up to date
"""

import argparse
import ast
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10 (tomllib is 3.11+); regex fallback below
    tomllib = None  # type: ignore[assignment]

METAPACKAGE_ROOT = Path(__file__).resolve().parent.parent

OLD_PACKAGE = "render_sdk"
NEW_PACKAGE = "render"

HEADER = "# Generated by scripts/generate_mirror.py - do not edit.\n"

LEAF_TEMPLATE = """\
{header}# Compatibility alias: {old_name} -> {new_name}
if __name__ == "__main__":
    import runpy

    runpy.run_module("{new_name}", run_name="__main__", alter_sys=True)
else:
    import importlib
    import sys

    sys.modules[__name__] = importlib.import_module("{new_name}")
"""

PACKAGE_TEMPLATE = """\
{header}# Compatibility alias package: {old_name} -> {new_name}
#
# This package keeps its own sys.modules identity (self-aliasing would point
# __path__ at the real directory and re-execute real sources under {old_name}
# names) but forwards ALL attribute access to the real package, so every
# attribute reachable through it is the real object.
import importlib
import sys
import types

_real = importlib.import_module("{new_name}")

__doc__ = _real.__doc__
{all_assignment}

class _AliasPackage(types.ModuleType):
    def __getattr__(self, name):
        return getattr(_real, name)

    def __dir__(self):
        return dir(_real)

    def __setattr__(self, name, value):
        # After loading a child module the import system binds it onto this
        # package (setattr(parent, "task", <module>)). The real package may
        # shadow that name with a same-named attribute (render.workflows.task
        # is the task decorator, not the submodule); mirroring must not let
        # the child binding change what the attribute resolves to. Drop any
        # module binding that diverges from the real package's attribute.
        if (
            isinstance(value, types.ModuleType)
            and getattr(_real, name, value) is not value
        ):
            return
        super().__setattr__(name, value)


sys.modules[__name__].__class__ = _AliasPackage
"""

# The top-level package additionally emits the deprecation warning, before
# anything that could fail if `render` is missing.
ROOT_PREAMBLE = """\
import warnings

warnings.warn(
    "The 'render_sdk' package has been renamed to 'render'. "
    "'render_sdk' is now a compatibility shim; "
    "install 'render' and update imports from 'render_sdk' to 'render'.",
    DeprecationWarning,
    stacklevel=2,
)

"""


class MirrorError(Exception):
    """A real-source shape the generator refuses to mirror silently."""


def _collect_bindings(body: list[ast.stmt], source_path: Path) -> list[str]:
    """Names bound at module top level, descending into if/try bodies.

    Descending into `if` covers `if TYPE_CHECKING:` (which is how the real
    package exposes its lazy attributes to type checkers) and version guards.
    Plain `import X` statements are skipped: re-exporting stdlib module names
    from the shim would be noise, and nothing in the SDK's public surface is
    reached that way.
    """
    names: list[str] = []
    for node in body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.append(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.append(target.id)
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name):
                names.append(node.target.id)
        elif isinstance(node, ast.ImportFrom):
            if node.module == "__future__":
                continue
            for alias in node.names:
                if alias.name == "*":
                    raise MirrorError(
                        f"{source_path}: star import found; the stub generator "
                        "cannot enumerate its bindings. Replace it with "
                        "explicit imports or teach the generator about it."
                    )
                names.append(alias.asname or alias.name)
        elif isinstance(node, ast.If):
            names += _collect_bindings(node.body, source_path)
            names += _collect_bindings(node.orelse, source_path)
        elif isinstance(node, ast.Try):
            names += _collect_bindings(node.body, source_path)
            for handler in node.handlers:
                names += _collect_bindings(handler.body, source_path)
            names += _collect_bindings(node.orelse, source_path)
            names += _collect_bindings(node.finalbody, source_path)
    return names


def _extract_all(tree: ast.Module, source_path: Path) -> list[str] | None:
    """The module's __all__ as a list of strings, or None if absent."""
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets):
            continue
        if not isinstance(node.value, (ast.List, ast.Tuple)):
            raise MirrorError(f"{source_path}: __all__ is not a list/tuple literal")
        entries: list[str] = []
        for elt in node.value.elts:
            if not isinstance(elt, ast.Constant) or not isinstance(elt.value, str):
                raise MirrorError(
                    f"{source_path}: __all__ contains a non-string-literal entry"
                )
            entries.append(elt.value)
        return entries
    return None


def _is_dunder(name: str) -> bool:
    return name.startswith("__") and name.endswith("__")


def _exported_names(source_path: Path) -> tuple[list[str], list[str] | None]:
    """(stub re-export names, __all__ entries or None) for a real module."""
    tree = ast.parse(source_path.read_text(), filename=str(source_path))
    dunder_all = _extract_all(tree, source_path)
    bound = _collect_bindings(tree.body, source_path)

    keep_dunders = set(dunder_all or ())
    names: list[str] = []
    seen: set[str] = set()
    for name in bound:
        if name == "__all__":
            continue
        if _is_dunder(name) and name not in keep_dunders:
            continue
        if name not in seen:
            seen.add(name)
            names.append(name)

    if dunder_all is not None:
        missing = [n for n in dunder_all if n not in seen]
        for name in missing:
            # An __all__ entry with no top-level binding must be a submodule.
            parent = source_path.parent
            if (parent / f"{name}.py").exists() or (
                parent / name / "__init__.py"
            ).exists():
                names.append(name)
                seen.add(name)
            else:
                raise MirrorError(
                    f"{source_path}: __all__ entry {name!r} is neither a "
                    "top-level binding nor a submodule"
                )
    return sorted(names), dunder_all


def _format_all(entries: list[str]) -> str:
    if not entries:
        return "__all__ = []\n"
    lines = "".join(f'    "{entry}",\n' for entry in entries)
    return f"__all__ = [\n{lines}]\n"


def _stub_content(new_name: str, names: list[str], all_: list[str] | None) -> str:
    parts = [HEADER]
    if names:
        imports = "".join(f"    {n} as {n},\n" for n in names)
        parts.append(f"from {new_name} import (\n{imports})\n")
    if all_ is not None:
        parts.append("\n" + _format_all(all_))
    return "".join(parts)


def _package_shim(old_name: str, new_name: str, star_names: list[str]) -> str:
    body = PACKAGE_TEMPLATE.format(
        header=HEADER,
        old_name=old_name,
        new_name=new_name,
        all_assignment=_format_all(star_names),
    )
    if old_name == OLD_PACKAGE:
        # Warning goes after the header comment, before everything else.
        comment_end = body.index("import importlib")
        body = body[:comment_end] + ROOT_PREAMBLE + body[comment_end:]
    return body


def generate(sdk_root: Path) -> dict[Path, str]:
    """All mirror files, keyed by path relative to the render_sdk/ root."""
    package_root = sdk_root / NEW_PACKAGE
    if not (package_root / "__init__.py").exists():
        raise MirrorError(f"real package not found at {package_root}")

    outputs: dict[Path, str] = {}
    for real_path in sorted(package_root.rglob("*")):
        if "__pycache__" in real_path.parts or not real_path.is_file():
            continue
        rel = real_path.relative_to(package_root)
        if real_path.name == "py.typed":
            outputs[rel] = ""
            continue
        if real_path.suffix != ".py":
            continue

        dotted_rel = ".".join(
            rel.parts[:-1] + ((rel.stem,) if rel.stem != "__init__" else ())
        )
        new_name = f"{NEW_PACKAGE}.{dotted_rel}" if dotted_rel else NEW_PACKAGE
        old_name = f"{OLD_PACKAGE}.{dotted_rel}" if dotted_rel else OLD_PACKAGE

        names, dunder_all = _exported_names(real_path)
        if rel.name == "__init__.py":
            # Star-import surface: the real __all__ verbatim (order preserved),
            # or the public bindings when the real package declares none.
            star_names = (
                dunder_all
                if dunder_all is not None
                else [n for n in names if not n.startswith("_")]
            )
            outputs[rel] = _package_shim(old_name, new_name, star_names)
        else:
            outputs[rel] = LEAF_TEMPLATE.format(
                header=HEADER, old_name=old_name, new_name=new_name
            )
        outputs[rel.with_suffix(".pyi")] = _stub_content(new_name, names, dunder_all)
    return outputs


def _synced_pyproject(pyproject: Path, version: str) -> str:
    """Metapackage pyproject text with version and render pins set."""
    text = pyproject.read_text()
    text, n_version = re.subn(
        r'(?m)^version = "[^"]*"', f'version = "{version}"', text, count=1
    )
    text, n_pins = re.subn(
        r'"render(\[[^\]]*\])?==[^"]*"', rf'"render\g<1>=={version}"', text
    )
    if n_version != 1 or n_pins < 1:
        raise MirrorError(
            f"{pyproject}: expected a version field and at least one "
            f'"render==..." pin to sync (found {n_version} and {n_pins})'
        )
    return text


def _sdk_version(sdk_root: Path) -> str:
    pyproject = sdk_root / "pyproject.toml"
    if tomllib is not None:
        with open(pyproject, "rb") as f:
            return tomllib.load(f)["project"]["version"]
    match = re.search(r'(?m)^version = "([^"]+)"', pyproject.read_text())
    if match is None:
        raise MirrorError(f"{pyproject}: no version field found")
    return match.group(1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sdk-root",
        type=Path,
        default=METAPACKAGE_ROOT.parent / "python",
        help="Root of the real SDK project (contains pyproject.toml and render/)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=METAPACKAGE_ROOT / OLD_PACKAGE,
        help="Output directory for the mirror package",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the mirror and pyproject pins are up to date; write nothing",
    )
    args = parser.parse_args()

    try:
        outputs = generate(args.sdk_root)
        pyproject = METAPACKAGE_ROOT / "pyproject.toml"
        synced_pyproject = _synced_pyproject(pyproject, _sdk_version(args.sdk_root))
    except MirrorError as err:
        print(f"ERROR: {err}", file=sys.stderr)
        return 1

    existing = {
        path.relative_to(args.out)
        for path in args.out.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    }
    orphans = sorted(existing - outputs.keys())

    errors: list[str] = []
    if args.check:
        for rel, content in sorted(outputs.items()):
            target = args.out / rel
            if not target.exists():
                errors.append(f"missing generated file: {target}")
            elif target.read_text() != content:
                errors.append(f"generated file out of date: {target}")
        for rel in orphans:
            errors.append(f"orphaned file (no real module): {args.out / rel}")
        if pyproject.read_text() != synced_pyproject:
            errors.append(f"version pins out of date: {pyproject}")
        if errors:
            for err in errors:
                print(f"ERROR: {err}", file=sys.stderr)
            return 1
        print(f"Mirror is up to date ({len(outputs)} files).")
        return 0

    for rel, content in sorted(outputs.items()):
        target = args.out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text() != content:
            target.write_text(content)
    for rel in orphans:
        (args.out / rel).unlink()
        print(f"Removed orphan {args.out / rel}")
    if pyproject.read_text() != synced_pyproject:
        pyproject.write_text(synced_pyproject)
    print(f"Generated {len(outputs)} files under {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
